### ISSUE TITLE
Suppor for list elements

### ISSUE THREAD

**Issue by go2sujeet** [tovic/rich-text-editor#11]
Hi, I really like the way the editor is simple, light -weight.
I'm just wondering why doesn't this have a provision for list elements and what does it takes to add list elements to the same?

Thanks
Sujeet

**Comment by taufik-nurrohman** [comment]
@sujeetbuddiga Block elements are not allowed in this editor. FYI, the paragraph element is automatically generated simply by replacing two empty line break into `</p><p>`. This rich text editor was created to be used on public form, especially for a chat-like form, so we only support inline modifier like bold, italic and link for simplicity.

**Comment by go2sujeet** [comment]
thanks for the response @tovic 

is it scoped out? or is it in not yet kind of state?

**Comment by taufik-nurrohman** [comment]
Scoped out, sorry. Let me give you a simple example. In your text editor you have this:

~~~ .html
asdf

asdf
asdf
~~~

So you get this output:

~~~ .php
<p>asdf</p>
<p>asdf<br>asdf</p>
~~~

Then you decided to have a list feature, so you end-up giving this:

~~~ .html
asdf

<ul>
<li>asdf</li>
<li>asdf</li>
</ul>

asdf
asdf
~~~

So you will end-up with this:

~~~ .php
<p>asdf</p>
<p><ul><br><li>asdf</li><br><li>asdf</li><br></ul></p>
<p>asdf<br>asdf</p>
~~~

**Comment by go2sujeet** [comment]
Yeah, I understand.

Thanks for responding patiently :D
