### ISSUE TITLE
Paste on Mobile removes pasted content immediately

### ISSUE THREAD

**Issue by robmarshall** [tovic/rich-text-editor#8]
When tested on Apple and Android mobile devices (both on chrome so far) the paste function is not working. As far I can tell the function is being triggered (I extended the paste delay) but as soon as the delay is up it seems the content is not found in "view" and is removed.

**Comment by taufik-nurrohman** [comment]
https://github.com/tovic/rich-text-editor/commit/a330d78ed16cbfd8dded8a55aaf9d6ed2d39bde3
