### ISSUE TITLE
Positioning

### ISSUE THREAD

**Issue by tomsx** [tovic/rich-text-editor#9]
How can I set the (absolute) position of the editor? There are no top, left, height, width properties.
I currently use  $('.rich-text-editor.view.expand').css('top','160px'); but this doesn't work if there is more than one editor since they all have the same classes and there are no id or name attributes to differentiate between them.

**Comment by taufik-nurrohman** [comment]
Wrapping it with a custom element?

~~~ .html
<div style="position:absolute;top:0;left:0;">
  <textarea></textarea>
  <script>new RTE(document.querySelector('textarea'));</script>
</div>
~~~

You can also do this for targetting specific instance:

~~~ .js
var editor = new RTE(document.querySelector('textarea'));

$(editor.container).css('top', '160px');
~~~

~~~ .js
new RTE(document.querySelector('textarea[name="foo"]'));
new RTE(document.querySelector('textarea[name="bar"]'));
new RTE(document.querySelector('textarea[name="baz"]'));

$(RTE.__instance__.foo).css('top', '160px');
~~~

**Comment by tomsx** [comment]
Thank you so much!
